// <auto-generated>
//     Generated by tools/generate-glyphs.cs. Do not edit by hand.
//     Mirrored from iconfont.maui.fluenticons 1.1.0.
// </auto-generated>

namespace AniSprinkles.Icons;

/// <summary>
/// Fluent icon glyphs mirrored from <c>IconFont.Maui.FluentIcons</c>, which ships platform-only
/// TFMs and so cannot be referenced from this <c>net10.0</c> library. Only the glyphs Core actually
/// uses are mirrored; XAML and the MAUI app project keep using the package directly.
/// <para>
/// <c>IconGlyphReferenceTests</c> asserts every constant here still matches the package by name and
/// value, so this copy cannot drift. Regenerate with <c>dotnet run tools/generate-glyphs.cs</c>.
/// </para>
/// </summary>
public static class Glyphs
{
    /// <summary>Mirrors <c>FluentIconsRegular</c>.</summary>
    public static class Regular
    {
        public const string AddCircle24 = "\uf10d";
        public const string Alert24 = "\uf115";
        public const string ArrowRepeatAll24 = "\uf172";
        public const string ArrowSortDownLines24 = "\ue0f2";
        public const string ArrowSortUpLines24 = "\udb81\udd58";
        public const string ArrowTrending24 = "\uf198";
        public const string Book24 = "\uf8fe";
        public const string BookOpen24 = "\ue179";
        public const string Bookmark24 = "\uf1f6";
        public const string Calendar24 = "\ue24f";
        public const string CalendarClock24 = "\uf21e";
        public const string CalendarPlay24 = "\uf0af";
        public const string Checkmark24 = "\uf295";
        public const string CheckmarkCircle24 = "\uf299";
        public const string Clock24 = "\uf2de";
        public const string CloudDismiss24 = "\ue3a0";
        public const string Delete24 = "\uf34d";
        public const string DismissCircle24 = "\uf36e";
        public const string DocumentOnePage24 = "\uf39a";
        public const string Edit24 = "\uf3de";
        public const string ErrorCircle24 = "\uf3f2";
        public const string Eye24 = "\ue5f3";
        public const string EyeOff24 = "\ue5f6";
        public const string Feed24 = "\ueef9";
        public const string Fire24 = "\uef6a";
        public const string FolderArrowRight24 = "\ue64d";
        public const string FontFamily = "FluentIcons";
        public const string GlobeVideo24 = "\uf461";
        public const string Grid24 = "\uf463";
        public const string Heart24 = "\uf47a";
        public const string Info24 = "\uf4a4";
        public const string Library24 = "\uf4d3";
        public const string List24 = "\uf4ee";
        public const string LockClosed24 = "\ue790";
        public const string MoviesAndTv24 = "\uf55a";
        public const string MusicNote224 = "\ue855";
        public const string PauseCircle24 = "\ue8cf";
        public const string People24 = "\uf5a9";
        public const string Person48 = "\uf5c0";
        public const string Rocket24 = "\uf678";
        public const string Search24 = "\uf690";
        public const string Settings24 = "\uf6aa";
        public const string Sparkle24 = "\ueb34";
        public const string Star24 = "\uf710";
        public const string TextBulletListSquare24 = "\uf7a9";
        public const string ThumbLike24 = "\uf820";
        public const string Trophy24 = "\uf837";
        public const string Tv24 = "\uedc3";
        public const string VideoShort24 = "\udb82\udf2b";
        public const string WifiOff24 = "\uee5a";
    }

    /// <summary>Mirrors <c>FluentIconsFilled</c>.</summary>
    public static class Filled
    {
        public const string Feed24 = "\ueef9";
        public const string FontFamily = "FluentIconsFilled";
        public const string Heart24 = "\uf47e";
        public const string Library24 = "\uf4dd";
        public const string Rocket24 = "\uf682";
        public const string Search24 = "\uf69a";
        public const string Settings24 = "\uf6b3";
    }
}
