// Regenerates src/AniSprinkles.Core/Icons/Glyphs.cs.
//
// IconFont.Maui.FluentIcons only ships platform TFMs (net10.0-android36.0 / -ios26.0 /
// -maccatalyst26.0), so AniSprinkles.Core — which targets plain net10.0 so the unit tests can
// reference it — cannot use the package. Core mirrors just the glyphs it references as its own
// constants instead. The MAUI app project and every .xaml file keep using the real package.
//
// The mirror is kept honest by IconGlyphReferenceTests, which asserts every constant here still
// matches the package by name AND value. If that test fails, run this and commit the result.
//
// Usage (from the repo root):
//   dotnet run tools/generate-glyphs.cs
//   dotnet run tools/generate-glyphs.cs -- <scanDir> <outFile> [iconFontDll]

using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using System.Text;
using System.Text.RegularExpressions;

const string PackageId = "iconfont.maui.fluenticons";
const string PackageVersion = "1.1.0";
const string AssemblyFileName = "IconFont.Maui.FluentIcons.dll";

var repoRoot = FindRepoRoot();
var scanDir = args.Length > 0 ? args[0] : Path.Combine(repoRoot, "src", "AniSprinkles.Core");
var outFile = args.Length > 1
    ? args[1]
    : Path.Combine(repoRoot, "src", "AniSprinkles.Core", "Icons", "Glyphs.cs");
var dllPath = args.Length > 2 ? args[2] : ResolvePackageAssembly();

Console.WriteLine($"scan   {scanDir}");
Console.WriteLine($"icons  {dllPath}");
Console.WriteLine($"out    {outFile}");

// Which members does the C# actually reference? Anything unreferenced stays out: the package
// declares 9,223 Regular and 9,360 Filled literals and mirroring all of them would be absurd.
var wanted = new Dictionary<string, SortedSet<string>>(StringComparer.Ordinal)
{
    ["FluentIconsRegular"] = new(StringComparer.Ordinal),
    ["FluentIconsFilled"] = new(StringComparer.Ordinal),
};

var reference = new Regex(@"\b(FluentIconsRegular|FluentIconsFilled)\.([A-Za-z_][A-Za-z0-9_]*)");
foreach (var file in Directory.EnumerateFiles(scanDir, "*.cs", SearchOption.AllDirectories))
{
    if (file.Contains($"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}") ||
        file.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}"))
    {
        continue;
    }

    foreach (Match m in reference.Matches(File.ReadAllText(file)))
    {
        wanted[m.Groups[1].Value].Add(m.Groups[2].Value);
    }
}

// Also keep whatever the current Glyphs.cs already declares, so regenerating after the call sites
// have been rewritten to Glyphs.* does not silently empty the file.
if (File.Exists(outFile))
{
    var existing = File.ReadAllText(outFile);
    foreach (Match m in Regex.Matches(existing, @"public const string ([A-Za-z_][A-Za-z0-9_]*)"))
    {
        var member = m.Groups[1].Value;
        var beforeMember = existing[..m.Index];
        var cls = beforeMember.LastIndexOf("class Filled", StringComparison.Ordinal) >
                  beforeMember.LastIndexOf("class Regular", StringComparison.Ordinal)
            ? "FluentIconsFilled"
            : "FluentIconsRegular";
        wanted[cls].Add(member);
    }
}

var values = ReadLiterals(dllPath, wanted.Keys);

var missing = wanted
    .SelectMany(kv => kv.Value.Select(m => (Type: kv.Key, Member: m)))
    .Where(x => !values[x.Type].ContainsKey(x.Member))
    .ToList();

if (missing.Count > 0)
{
    foreach (var (type, member) in missing)
    {
        Console.Error.WriteLine($"error: {type}.{member} does not exist in {AssemblyFileName}");
    }

    return 1;
}

var sb = new StringBuilder();
sb.AppendLine("// <auto-generated>");
sb.AppendLine("//     Generated by tools/generate-glyphs.cs. Do not edit by hand.");
sb.AppendLine($"//     Mirrored from {PackageId} {PackageVersion}.");
sb.AppendLine("// </auto-generated>");
sb.AppendLine();
sb.AppendLine("namespace AniSprinkles.Icons;");
sb.AppendLine();
sb.AppendLine("/// <summary>");
sb.AppendLine("/// Fluent icon glyphs mirrored from <c>IconFont.Maui.FluentIcons</c>, which ships platform-only");
sb.AppendLine("/// TFMs and so cannot be referenced from this <c>net10.0</c> library. Only the glyphs Core actually");
sb.AppendLine("/// uses are mirrored; XAML and the MAUI app project keep using the package directly.");
sb.AppendLine("/// <para>");
sb.AppendLine("/// <c>IconGlyphReferenceTests</c> asserts every constant here still matches the package by name and");
sb.AppendLine("/// value, so this copy cannot drift. Regenerate with <c>dotnet run tools/generate-glyphs.cs</c>.");
sb.AppendLine("/// </para>");
sb.AppendLine("/// </summary>");
sb.AppendLine("public static class Glyphs");
sb.AppendLine("{");
Emit(sb, "Regular", "FluentIconsRegular");
sb.AppendLine();
Emit(sb, "Filled", "FluentIconsFilled");
sb.AppendLine("}");

Directory.CreateDirectory(Path.GetDirectoryName(outFile)!);
File.WriteAllText(outFile, sb.ToString());

var total = wanted.Sum(kv => kv.Value.Count);
Console.WriteLine($"wrote {total} constants");
return 0;

void Emit(StringBuilder builder, string nestedName, string sourceType)
{
    builder.AppendLine($"    /// <summary>Mirrors <c>{sourceType}</c>.</summary>");
    builder.AppendLine($"    public static class {nestedName}");
    builder.AppendLine("    {");
    foreach (var member in wanted[sourceType])
    {
        builder.AppendLine($"        public const string {member} = {Literal(values[sourceType][member])};");
    }

    builder.AppendLine("    }");
}

static string Literal(string value)
{
    var sb = new StringBuilder("\"");
    foreach (var ch in value)
    {
        // Glyph values are private-use-area code points. Escaping them keeps the generated file
        // pure ASCII, so it survives any encoding and stays readable in a diff.
        sb.Append(ch is >= ' ' and <= '~' && ch != '"' && ch != '\\'
            ? ch.ToString()
            : $"\\u{(int)ch:x4}");
    }

    return sb.Append('"').ToString();
}

static Dictionary<string, Dictionary<string, string>> ReadLiterals(string dll, IEnumerable<string> typeNames)
{
    var result = typeNames.ToDictionary(
        n => n,
        _ => new Dictionary<string, string>(StringComparer.Ordinal),
        StringComparer.Ordinal);

    using var stream = File.OpenRead(dll);
    using var pe = new PEReader(stream);
    var md = pe.GetMetadataReader();

    foreach (var handle in md.TypeDefinitions)
    {
        var type = md.GetTypeDefinition(handle);
        var name = md.GetString(type.Name);
        if (!result.TryGetValue(name, out var bucket))
        {
            continue;
        }

        foreach (var fieldHandle in type.GetFields())
        {
            var field = md.GetFieldDefinition(fieldHandle);
            if (!field.Attributes.HasFlag(FieldAttributes.Literal))
            {
                continue;
            }

            var constantHandle = field.GetDefaultValue();
            if (constantHandle.IsNil)
            {
                continue;
            }

            var constant = md.GetConstant(constantHandle);
            if (constant.TypeCode != ConstantTypeCode.String)
            {
                continue;
            }

            var blob = md.GetBlobReader(constant.Value);
            bucket[md.GetString(field.Name)] = blob.ReadUTF16(blob.Length);
        }
    }

    return result;
}

static string ResolvePackageAssembly()
{
    var root = Environment.GetEnvironmentVariable("NUGET_PACKAGES")
        ?? Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
            ".nuget",
            "packages");

    var libRoot = Path.Combine(root, PackageId, PackageVersion, "lib");
    if (!Directory.Exists(libRoot))
    {
        throw new DirectoryNotFoundException(
            $"{PackageId} {PackageVersion} is not in the package cache at {libRoot}. Restore first, or pass the .dll path.");
    }

    // Any TFM will do — the glyph literals are identical across them.
    var found = Directory
        .EnumerateFiles(libRoot, AssemblyFileName, SearchOption.AllDirectories)
        .OrderBy(p => p, StringComparer.Ordinal)
        .FirstOrDefault();

    return found ?? throw new FileNotFoundException($"{AssemblyFileName} not found under {libRoot}.");
}

static string FindRepoRoot()
{
    // Walks up from the working directory, not AppContext.BaseDirectory: a file-based app runs out
    // of a temp build directory that has no relationship to the repo.
    var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
    while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "AniSprinkles.slnx")))
    {
        dir = dir.Parent;
    }

    return dir?.FullName ?? Directory.GetCurrentDirectory();
}
